// Generated by scripts/crop-chakras.mjs — do not edit by hand.

export type Chakra = {
  order: number;
  id: string;
  name: string;
  english: string;
  bija: string;
  petals: number;
  /** one-line description shown under the disc in focus */
  note: string;
  /** circular PNG cropped from the source plate, transparent corners */
  file: string;
  size: [number, number];
  /** sampled from the disc itself — mid is its average colour */
  colors: { light: string; mid: string; deep: string };
};

export const CHAKRAS: Chakra[] = [
  {
    "order": 1,
    "id": "muladhara",
    "note": "Ground and steady — the base the whole system stands on.",
    "name": "Muladhara",
    "english": "Root",
    "bija": "लं",
    "petals": 4,
    "file": "/chakras/01-muladhara.png",
    "size": [
      359,
      362
    ],
    "colors": {
      "light": "#A7361D",
      "mid": "#732514",
      "deep": "#341109"
    }
  },
  {
    "order": 2,
    "id": "svadhishthana",
    "note": "Feeling and flow — creativity, appetite and emotional movement.",
    "name": "Svadhishthana",
    "english": "Sacral",
    "bija": "वं",
    "petals": 6,
    "file": "/chakras/02-svadhishthana.png",
    "size": [
      362,
      363
    ],
    "colors": {
      "light": "#FB711D",
      "mid": "#AD4E14",
      "deep": "#4E2309"
    }
  },
  {
    "order": 3,
    "id": "manipura",
    "note": "Will and fire — confidence, drive and a sense of your own power.",
    "name": "Manipura",
    "english": "Solar Plexus",
    "bija": "रं",
    "petals": 10,
    "file": "/chakras/03-manipura.png",
    "size": [
      362,
      363
    ],
    "colors": {
      "light": "#FFA824",
      "mid": "#B17419",
      "deep": "#50340B"
    }
  },
  {
    "order": 4,
    "id": "anahata",
    "note": "Love and connection — where compassion meets the courage to open.",
    "name": "Anahata",
    "english": "Heart",
    "bija": "यं",
    "petals": 12,
    "file": "/chakras/04-anahata.png",
    "size": [
      360,
      365
    ],
    "colors": {
      "light": "#738A34",
      "mid": "#4F5F24",
      "deep": "#242B10"
    }
  },
  {
    "order": 5,
    "id": "vishuddha",
    "note": "Voice and truth — expression, honesty and being heard.",
    "name": "Vishuddha",
    "english": "Throat",
    "bija": "हं",
    "petals": 16,
    "file": "/chakras/05-vishuddha.png",
    "size": [
      364,
      365
    ],
    "colors": {
      "light": "#3A7883",
      "mid": "#28535A",
      "deep": "#122529"
    }
  },
  {
    "order": 6,
    "id": "ajna",
    "note": "Insight and perception — the way you see before you think.",
    "name": "Ajna",
    "english": "Third Eye",
    "bija": "ॐ",
    "petals": 2,
    "file": "/chakras/06-ajna.png",
    "size": [
      361,
      364
    ],
    "colors": {
      "light": "#614E74",
      "mid": "#433650",
      "deep": "#1E1824"
    }
  },
  {
    "order": 7,
    "id": "sahasrara",
    "note": "Awareness and unity — the widest view, beyond the personal.",
    "name": "Sahasrara",
    "english": "Crown",
    "bija": "ॐ",
    "petals": 1000,
    "file": "/chakras/07-sahasrara.png",
    "size": [
      365,
      370
    ],
    "colors": {
      "light": "#9D648B",
      "mid": "#6C4560",
      "deep": "#311F2B"
    }
  }
];
